
module.exports = { protocol_preamble: { Version: '2.7' },
  videohub_device: 
   { 'Device present': 'true',
     'Model name': 'Blackmagic Smart Videohub 20 x 20',
     'Friendly name': 'Smart Videohub 20 x 20',
     'Unique ID': '7C2E0D0361DE',
     'Video inputs': '20',
     'Video processing units': '0',
     'Video outputs': '20',
     'Video monitoring outputs': '0',
     'Serial ports': '0' },
  input_labels: 
   [ 'Cam 1',
     'Cam 2',
     'Cam 3',
     'A',
     'B',
     'GFX 1',
     'GFX 2',
     'Prompter',
     'Input 9',
     'Input 10',
     'Input 11',
     'Input 12',
     'Input 13',
     'Input 14',
     'Input 15',
     'PROGRAM',
     'Input 17',
     'Input 18',
     'Input 19',
     'Input 20' ],
  output_labels: 
   [ 'Output 1',
     'Output 2',
     'Output 3',
     'Output 4',
     'Output 5',
     'Output 6',
     'Output 7',
     'Output 8',
     'Output 9',
     'Output 10',
     'Records 1',
     'Records 2',
     'Records 3',
     'Output 14',
     'Output 15',
     'Output 16',
     'Output 17',
     'Output 18',
     'Output 19',
     'Output 20' ],
  video_output_locks: 
   [ 'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U',
     'U' ],
  video_output_routing: 
   [ '5',
     '7',
     '5',
     '7',
     '4',
     '5',
     '6',
     '7',
     '8',
     '9',
     '15',
     '15',
     '15',
     '15',
     '15',
     '15',
     '16',
     '17',
     '18',
     '19' ] };
